### ISSUE TITLE
空指针 from play.TypeResolver.exitFormalParameter(TypeResolver.java:96)

### ISSUE THREAD

**Issue by zbhuang2008** [RichardGong/PlayWithCompiler#27]
你好。我直接运行PlayScript.main, 然后就得到这个NPE.
然后我发现这个NPE在发生函数调用的例子里也会产生。

Exception in thread "main" java.lang.NullPointerException
	at play.TypeResolver.exitFormalParameter(TypeResolver.java:96)
	at play.PlayScriptParser$FormalParameterContext.exitRule(PlayScriptParser.java:940)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:47)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at play.PlayScriptCompiler.compile(PlayScriptCompiler.java:38)
	at play.PlayScript.main(PlayScript.java:96)

运行环境: Windows10 64bit + JDK8 + IntelliJ2019

Thanks.

**Comment by gofreelee** [comment]
你好，请问这个你怎么解决的？

**Comment by zbhuang2008** [comment]
Actually I did not solve the issue. I just revert back that change which was made on April 14th, then continue my learning.

**Comment by brianway** [comment]
+1，我也遇到了这个问题。
不止scratch.play文件，ClassTest.play，cloure.play 等多个文件均会报 java.lang.NullPointerException
